### ISSUE TITLE
Verify that database install documentation is clear and that dev and prod database are easy to setup.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/nldi-db#98]
We need easy to install "sample/development" and "complete/prod" database installs. The project already more or less has these options and documentation of how to install each locally needs to be clear. 

This issue can be closed once both options have been installed, the process documented carefully,  and followup issues have been opened.

**Comment by dblodgett-usgs** [comment]
Opened https://github.com/internetofwater/nldi-db/issues/100 to take care of some of this.

**Comment by dblodgett-usgs** [comment]
I've been working through a simplified full scale database install. I did some work on the (currently internal) database load project and opened #100 to move parts of that load into this repository. 

I've successfully gotten both the demo database and the prod database installed locally and will open a PR with some updates.

**Comment by gzt5142** [comment]
For a localized testing/demo/development database, the critical thing that I would want to see is the full NHD table(s), so that ingested features and be spatially joined to their comid counterparts from NHD. 

The feature table itself should be present, along with the feature_* tables from which it inherits... but those source-specific feature tables don't necessarily need to be fully populated.  Perhaps only one of the source tables can be fully populated, but the others only present with a handful of sample features present. 

The crawler_source table is so small that it can be included -- or can be loaded from its TSV in the repo at the time the test database is built locally.

**Comment by gzt5142** [comment]
Related note -- from our last conversation, I looked into what it would take to generalize the crawler_source such that it is not tied to a specific DB implementation.  

A simple repository pattern lets me load the crawler sources from CSV/TSV, JSON, Postgress DB... or even fake the crawler source table for unit-testing purposes.  Prototype in : 
 <https://github.com/gzt5142/nldi-crawler-py/blob/gt-src-repopattern/src/nldi_crawler/src.py>
